# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Dades\Projectes\Actius\Rovinya\Mapes\QTdisp\comandament.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(967, 684)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 941, 601))
        self.graphicsView.setObjectName("graphicsView")
        self.mesButton = QtWidgets.QPushButton(Dialog)
        self.mesButton.setGeometry(QtCore.QRect(10, 630, 75, 23))
        self.mesButton.setObjectName("mesButton")
        self.menysButton = QtWidgets.QPushButton(Dialog)
        self.menysButton.setGeometry(QtCore.QRect(90, 630, 75, 23))
        self.menysButton.setObjectName("menysButton")
        self.afegirButton = QtWidgets.QPushButton(Dialog)
        self.afegirButton.setGeometry(QtCore.QRect(310, 630, 75, 23))
        self.afegirButton.setObjectName("afegirButton")
        self.latEdit = QtWidgets.QLineEdit(Dialog)
        self.latEdit.setGeometry(QtCore.QRect(420, 630, 113, 20))
        self.latEdit.setText("")
        self.latEdit.setObjectName("latEdit")
        self.lonEdit = QtWidgets.QLineEdit(Dialog)
        self.lonEdit.setGeometry(QtCore.QRect(560, 630, 113, 20))
        self.lonEdit.setObjectName("lonEdit")
        self.obreButton = QtWidgets.QPushButton(Dialog)
        self.obreButton.setGeometry(QtCore.QRect(680, 630, 75, 23))
        self.obreButton.setObjectName("obreButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(390, 630, 47, 14))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(540, 630, 47, 14))
        self.label_2.setObjectName("label_2")
        self.netejaButton = QtWidgets.QPushButton(Dialog)
        self.netejaButton.setGeometry(QtCore.QRect(170, 630, 75, 23))
        self.netejaButton.setObjectName("netejaButton")
        self.connectaButton = QtWidgets.QPushButton(Dialog)
        self.connectaButton.setGeometry(QtCore.QRect(760, 630, 75, 23))
        self.connectaButton.setObjectName("connectaButton")
        self.cmdEdit = QtWidgets.QLineEdit(Dialog)
        self.cmdEdit.setGeometry(QtCore.QRect(562, 660, 191, 20))
        self.cmdEdit.setObjectName("cmdEdit")
        self.enviaButton = QtWidgets.QPushButton(Dialog)
        self.enviaButton.setGeometry(QtCore.QRect(760, 660, 75, 23))
        self.enviaButton.setObjectName("enviaButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(500, 660, 47, 14))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mesButton.setText(_translate("Dialog", "Zoom +"))
        self.menysButton.setText(_translate("Dialog", "Zoom -"))
        self.afegirButton.setText(_translate("Dialog", "Afegir punt"))
        self.obreButton.setText(_translate("Dialog", "Obre fitxer"))
        self.label.setText(_translate("Dialog", "Lat."))
        self.label_2.setText(_translate("Dialog", "Lon."))
        self.netejaButton.setText(_translate("Dialog", "Neteja"))
        self.connectaButton.setText(_translate("Dialog", "Connecta"))
        self.enviaButton.setText(_translate("Dialog", "Envia"))
        self.label_3.setText(_translate("Dialog", "Comanda"))
